# Generated by Django 4.0.4 on 2022-07-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('propiedades', models.CharField(max_length=250)),
                ('conservacion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Recet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ingredientes', models.CharField(max_length=250)),
                ('tiempo', models.IntegerField()),
                ('preparacion', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingrediente_dos',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingrediente_tres',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingrediente_uno',
            field=models.CharField(max_length=250),
        ),
    ]
